# ./dev.dockerfile
services:
  react-app:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true