name: Build and Push on Master Push

# Triggers the workflow on push events to the master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Specifies the runner environment
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud Artifact Registry (placeholder)
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
      # Uncomment and configure the next step when deciding to use Google Cloud Artifact Registry
      # - name: Configure Docker for Google Cloud Artifact Registry
      #   run: gcloud auth configure-docker <REGION>-docker.pkg.dev

    - name: Build and tag the Docker image
      run: |
        docker build . -t <REGION>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/your-repo/your-image:latest

    # Uncomment the next step to push the image to Google Cloud Artifact Registry
    # - name: Push the Docker image
    #   run: docker push <REGION>-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/your-repo/your-image:latest
